#!/bin/sh

echo "----------------------------"
echo "--- HERE I AM IN cleanup ---"
echo "----------------------------"

# should start in package root dir
rm -f src/gdxlib/*.o src/gdxlib/*.dylib src/gdxlib/*.so
